#!/usr/bin/env bash
# Installs skills from metamask-extension-skills into the consuming repo.
#
# Usage:
#   tools/install.sh --repo metamask-extension --target ~/dev/metamask/metamask-extension
#   tools/install.sh --repo metamask-extension --target ~/dev/metamask/metamask-extension --dry-run
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO=""
TARGET=""
DRY_RUN=false

usage() {
  echo "Usage: $0 --repo <repo-name> --target <repo-path> [--dry-run]"
  echo
  echo "  --repo    GitHub repo name (e.g., metamask-extension)"
  echo "  --target  Path to the consuming repo"
  echo "  --dry-run Preview without writing files"
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)     REPO="$2"; shift 2 ;;
    --target)   TARGET="$2"; shift 2 ;;
    --dry-run)  DRY_RUN=true; shift ;;
    *) usage ;;
  esac
done

[[ -z "$REPO" || -z "$TARGET" ]] && usage
[[ ! -d "$TARGET" ]] && {
  echo "Error: target directory does not exist: $TARGET"
  exit 1
}

CLAUDE_DIR="$TARGET/.claude/skills"
CURSOR_DIR="$TARGET/.cursor/rules"
AGENTS_DIR="$TARGET/.agents/skills"

MANAGED_BANNER="<!-- DO NOT EDIT — Generated by metamask-extension-skills/tools/install.sh. Edit the source at https://github.com/MajorLift/metamask-extension-skills instead. -->"

log() { echo "  $1"; }
action() {
  if $DRY_RUN; then
    echo "  [dry-run] $1"
  else
    echo "  $1"
  fi
}

process_skill() {
  local skill_dir="$1"
  local skill_name
  skill_name=$(basename "$skill_dir")
  local base="$skill_dir/skill.md"
  local overlay="$skill_dir/repos/${REPO}.md"

  if [[ ! -f "$base" ]]; then
    echo "Warning: no skill.md in $skill_dir, skipping"
    return
  fi

  if [[ -d "$skill_dir/repos" && ! -f "$overlay" ]]; then
    log "skipped (no overlay for $REPO)"
    return
  fi

  local base_content
  base_content=$(awk 'BEGIN{n=0} /^---$/{n++; next} n>=2{print}' "$base")

  local overlay_content=""
  if [[ -f "$overlay" ]]; then
    overlay_content=$(awk 'BEGIN{n=0} /^---$/{n++; next} n>=2{print}' "$overlay")
  fi

  local fm
  fm=$(awk '/^---$/{n++; next} n==1{print} n>=2{exit}' "$base")
  local name
  name=$(echo "$fm" | grep '^name:' | sed 's/^name: *//')
  local description
  description=$(echo "$fm" | grep '^description:' | sed 's/^description: *//')
  local requires_line
  requires_line=$(echo "$fm" | grep '  - ' | sed 's/^  - //' || true)

  local knowledge_content=""
  if [[ -n "$requires_line" ]]; then
    local domain_dir
    domain_dir=$(dirname "$(dirname "$skill_dir")")
    while IFS= read -r ref; do
      local kfile="$domain_dir/knowledge/${ref}.md"
      if [[ -f "$kfile" ]]; then
        local kcontent
        kcontent=$(awk 'BEGIN{n=0} /^---$/{n++; next} n>=2{print}' "$kfile")
        knowledge_content="${knowledge_content}
${kcontent}
"
      fi
    done <<< "$requires_line"
  fi

  local merged="${base_content}"
  if [[ -n "$overlay_content" ]]; then
    merged="${merged}

${overlay_content}"
  fi

  if [[ -n "$knowledge_content" ]]; then
    merged="${merged}

---

## Reference Knowledge

${knowledge_content}"
  fi

  write_claude "$skill_name" "$name" "$description" "$merged"
  write_cursor "$skill_name" "$description" "$merged"
  write_agents "$skill_name" "$name" "$description" "$merged"
}

write_claude() {
  local skill_name="$1" name="$2" description="$3" content="$4"
  local dir="$CLAUDE_DIR/$skill_name"
  local file="$dir/SKILL.md"
  action "claude: .claude/skills/$skill_name/SKILL.md"
  if ! $DRY_RUN; then
    mkdir -p "$dir"
    cat > "$file" << HEREDOC
${MANAGED_BANNER}
---
name: ${name}
description: ${description}
---
${content}
HEREDOC
  fi
}

write_cursor() {
  local skill_name="$1" description="$2" content="$3"
  local dir="$CURSOR_DIR/$skill_name"
  local file="$dir/RULE.md"
  action "cursor: .cursor/rules/$skill_name/RULE.md"
  if ! $DRY_RUN; then
    mkdir -p "$dir"
    cat > "$file" << HEREDOC
${MANAGED_BANNER}
---
description: ${description}
alwaysApply: false
---
${content}
HEREDOC
  fi
}

write_agents() {
  local skill_name="$1" name="$2" description="$3" content="$4"
  local dir="$AGENTS_DIR/$skill_name"
  local skill_file="$dir/SKILL.md"
  local yaml_dir="$dir/agents"
  local yaml_file="$yaml_dir/openai.yaml"
  action "agents: .agents/skills/$skill_name/SKILL.md"
  action "agents: .agents/skills/$skill_name/agents/openai.yaml"
  if ! $DRY_RUN; then
    mkdir -p "$yaml_dir"
    cat > "$skill_file" << HEREDOC
${MANAGED_BANNER}
---
name: ${name}
description: ${description}
---
${content}
HEREDOC
    cat > "$yaml_file" << HEREDOC
interface:
  display_name: '${name}'
  short_description: '${description}'
  default_prompt: 'Use \$${skill_name} for this task.'
HEREDOC
  fi
}

echo "metamask-extension-skills install"
echo "  repo:     $REPO"
echo "  target:   $TARGET"
echo "  dry-run:  $DRY_RUN"
echo

for local_domain_dir in "$REPO_ROOT"/domains/*/; do
  [[ -d "$local_domain_dir" ]] || continue
  domain_name=$(basename "$local_domain_dir")
  echo
  echo "Domain: $domain_name"
  for skill_dir in "$local_domain_dir"/skills/*/; do
    [[ -d "$skill_dir" ]] || continue
    log "skill: $(basename "$skill_dir")"
    process_skill "$skill_dir"
  done
done

echo
if $DRY_RUN; then
  echo "Dry run complete. No files written."
else
  echo "Install complete."
fi
